---
nextcloud_aio_image: nextcloud/all-in-one:latest

nextcloud_aio_mastercontainer_name: nextcloud-aio-mastercontainer

nextcloud_aio_config_volume: nextcloud_aio_mastercontainer

nextcloud_aio_admin_bind: "127.0.0.1"

nextcloud_aio_admin_port: 8080

nextcloud_aio_docker_sdk_package: python3-docker
