---
ssh_hardening_allow_users:
  - admin

ssh_hardening_allow_tcp_forwarding: "no"

ssh_hardening_kex_algorithms:
  - sntrup761x25519-sha512@openssh.com
  - curve25519-sha256
  - curve25519-sha256@libssh.org

ssh_hardening_ciphers:
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com

ssh_hardening_macs:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - umac-128-etm@openssh.com
