#!/usr/bin/env python3
"""Generate the hand-labelling worksheet from normalised findings.

Emits one YAML entry per first-party finding, keyed by fingerprint, pre-filled
with everything a human needs to judge it and with the four human fields left
empty. Nothing here proposes a verdict: the worksheet is filled in before any
triage run exists (`tasks.md - 3. Ground truth`).

Usage::

    normalise.py fixtures/baseline-scan.json | worksheet.py -o worksheet.yaml
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from vocabulary import DIFFICULTIES, VERDICTS  # noqa: E402

# The fields a human fills in. Kept empty by the generator, by design.
HUMAN_FIELDS = ("verdict", "evidence", "difficulty", "rationale")


class _Dumper(yaml.SafeDumper):
    """Renders an unfilled field as a blank rather than the word ``null``."""


def _represent_none(dumper: yaml.SafeDumper, _data: None) -> yaml.Node:
    return dumper.represent_scalar("tag:yaml.org,2002:null", "")


def _represent_str(dumper: yaml.SafeDumper, data: str) -> yaml.Node:
    """Keep multi-line values (the offending code) readable as block scalars."""
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_Dumper.add_representer(type(None), _represent_none)
_Dumper.add_representer(str, _represent_str)


def _render_code(lines: list[dict[str, Any]]) -> str:
    """The offending code as a numbered block, for reading in the worksheet."""
    if not lines:
        return ""
    width = max(len(str(line["number"])) for line in lines)
    return "\n".join(f"{str(line['number']).rjust(width)}  {line['content']}".rstrip() for line in lines)


def entry(record: dict[str, Any]) -> dict[str, Any]:
    filled = {
        "rule": record["rule_id"],
        "title": record["title"],
        "severity": record["severity"],
        "message": record["message"],
        "module": record["module_address"],
        "resource": record["resource_address"],
        "location": {
            "declared_in": f"{record['code_path']}:{record['start_line']}-{record['end_line']}",
            "instantiated_in": record["owner_path"],
        },
        "remediation": record["resolution"],
        "reference": record["primary_url"],
        "code": _render_code(record["code"]),
    }
    filled.update(dict.fromkeys(HUMAN_FIELDS))
    filled["evidence"] = []
    return filled


def build(normalised: dict[str, Any]) -> dict[str, Any]:
    return {record["fingerprint"]: entry(record) for record in normalised["first_party"]}


def header() -> str:
    lines = [
        "# Hand-labelling worksheet for first-party Trivy findings.",
        "#",
        "# Judge each finding on its own, even where several share a resource: a",
        "# per-resource decision collapses the corpus and inflates agreement.",
        "# Fill in all four fields on every entry.",
        "#",
        "#   verdict:    one of",
    ]
    lines += [f"#                 {name} - {meaning}" for name, meaning in VERDICTS.items()]
    lines += [
        "#   evidence:   the docs relied on, as repo-relative paths (may be empty",
        "#               only if the call needed none)",
        "#   difficulty: one of",
    ]
    lines += [f"#                 {name} - {meaning}" for name, meaning in DIFFICULTIES.items()]
    lines += [
        "#   rationale:  why, in your own words; a verdict without one is not a verdict",
        "#",
        "# Generated by worksheet.py. Keys are finding fingerprints; do not edit them.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "normalised",
        nargs="?",
        help="output of normalise.py; reads stdin when omitted",
    )
    parser.add_argument("-o", "--output", help="write here instead of stdout")
    args = parser.parse_args(argv)

    if args.normalised:
        with open(args.normalised, encoding="utf-8") as handle:
            normalised = json.load(handle)
    else:
        normalised = json.load(sys.stdin)

    rendered = header() + yaml.dump(
        build(normalised),
        Dumper=_Dumper,
        sort_keys=False,
        default_flow_style=False,
        width=88,
        allow_unicode=True,
    )

    if args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(rendered)
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
