name: Generate Terraform Documentation

on:
  pull_request:

permissions:
  contents: read

jobs:
  docs:
    name: Generate Terraform Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check Terraform docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          config-file: .terraform-docs.yml
          output-method: inject
          recursive: true
          git-push: true